name: flutter_map_training
description: Flutter application with google maps support for mobile and web platforms

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^6.0.0
  logging: ^1.1.0

  go_router: ^5.2.0
  
  #state
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5

  #network
  connectivity_plus: ^3.0.2
  dio: ^4.0.6

  #maps
  google_maps_flutter: ^2.2.1
  google_maps_flutter_web: ^0.4.0+3
  google_maps_cluster_manager: ^3.0.0+1
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true