// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk85RbMONp0vva3Otsd-AyMa9dBFKqJt0',
    appId: '1:759993335009:web:9be84b8328c1cd7e0bcba0',
    messagingSenderId: '759993335009',
    projectId: 'stations-map-app',
    authDomain: 'stations-map-app.firebaseapp.com',
    storageBucket: 'stations-map-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXwD-6kukVASbwlD3LPGyeZ3VdY6OHeuM',
    appId: '1:759993335009:android:22b1de23eef75d770bcba0',
    messagingSenderId: '759993335009',
    projectId: 'stations-map-app',
    storageBucket: 'stations-map-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjpxH-Ly947sRlze_YoYjz6zsMpMAyXkk',
    appId: '1:759993335009:ios:2a77068bab5814d60bcba0',
    messagingSenderId: '759993335009',
    projectId: 'stations-map-app',
    storageBucket: 'stations-map-app.appspot.com',
    iosClientId: '759993335009-qnrvj0naqftij8dnohju3j1olfivdtuu.apps.googleusercontent.com',
    iosBundleId: 'com.extrawest.flutterMapTraining',
  );
}
